### ISSUE TITLE
Add to F-droid

### ISSUE THREAD

**Issue by B0ycee** [piekarskipiotr/WakeOnLAN#1]
Hi,

Any chance you can add this to F-Droid?  https://f-droid.org/docs/FAQ_-_App_Developers/

Also, seems to have disappeared from Play store too?

Cheers.

**Comment by piekarskipiotr** [comment]
Hi,

Unfortunately I will not be able to add fdroid, the project is already very old and I have no plans to continue with it. The application has been removed from the store by Google :/

I'm sure you can find an existing solution in the store that will meet your needs.

**Comment by B0ycee** [comment]
Thanks for the reply.  There is no current WOL application on F-Droid, hence the ask :)
